import type { Metadata } from 'next';
import { Preahvihear, Poppins } from 'next/font/google';
import './globals.css';

const preahvihear = Preahvihear({
  subsets: ['latin'],
  weight: ['400'],
  style: 'normal',
  variable: '--preahvihear-font',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  style: 'normal',
  variable: '--poppins-font',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${preahvihear.className} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
